default:
  tags:
    - k8s

  image:
    name: release-ci.daocloud.io/product/ndx-mkdocs-material:3.1.3
    entrypoint: [ "" ]

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CI_DEBUG_TRACE: "true"

pages:
  only:
    - dao-i18n-badges
  stage: deploy
  script:
    - env
    - pwd
    - ls -al
    - whoami
    - ls /
    - pip install anybadge -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
    - pwd && cd /builds/ndx/product/frontend-i18n-counter/ && python i18n_counter/dao-i18n-badges.py # build project i18n badges svg
    - mkdocs build -f mkdocs.yml -d public/ # build to public path

  artifacts:
    paths:
      - public
    expire_in: 1 week
